"""Deterministic templates for a compliant Mermicorn repository."""

from __future__ import annotations

from textwrap import dedent


def readme(
    display_name: str,
    purpose_problem: str,
    first_proof: str,
    lane: str,
) -> str:
    return dedent(f"""\
    # {display_name}

    ## 1. What this project does
    {purpose_problem}

    ## 2. Who it is for
    Cherry and the Mermicorn Grove operators.

    ## 3. What exists today
    Foundation structure generated by mermicorn-mega-boot.

    ## 4. What is planned
    First proof artifact: `{first_proof}`.

    ## 5. What it does not claim
    No secrets, no false authority claims, no empty theater.

    ## 6. First proof artifact
    `{first_proof}`

    ## 7. Shared Mermicorn services
    See `mermicorn.repo.yaml` and the canonical registry at [mermicorn-grove](https://github.com/cyber-lazer-mermicorn/mermicorn-grove).

    ## 8. Information that remains private
    Secrets, credentials, and operational records stay in private layers or an external vault.

    ---
    *Generated by mermicorn-mega-boot. © Cherry.*
    """)


def status() -> str:
    return dedent("""\
    # Status

    **State:** FOUNDATION
    **Last updated:** generated by mermicorn-mega-boot

    Next: implement the first proof artifact declared in `mermicorn.repo.yaml`.
    """)


def roadmap(first_proof: str) -> str:
    return dedent(f"""\
    # Roadmap

    1. Complete foundation (done by mega-boot)
    2. Deliver first proof: `{first_proof}`
    3. Harden quality gates and examples
    4. Publish or promote when verified
    """)


def architecture() -> str:
    return dedent("""\
    # Architecture

    Follows the Mermicorn shared contract.
    Canonical integration state lives in mermicorn-grove.
    This repository owns its domain surface only.
    """)


def security() -> str:
    return dedent("""\
    # Security

    - No passwords, API keys, payment credentials, or government ID in this repository.
    - Use GitHub Secrets or an external vault for true secrets.
    - Public content is sanitized portfolio or template material only.
    """)


def contributing() -> str:
    return dedent("""\
    # Contributing

    Owned by Cherry (Cyber Lazer Mermicorn).
    Work on feature branches.
    Update STATUS.md and mermicorn.repo.yaml when state changes.
    Prefer atomic, descriptive commits.
    """)


def changelog() -> str:
    return dedent("""\
    # Changelog

    ## [Unreleased]
    - Scaffolded by mermicorn-mega-boot 0.1.0
    """)


def agents() -> str:
    return dedent("""\
    # Agents

    ## Primary Operator
    Cherry — domain judgment and final decisions.

    ## AI Support
    Operates under Mermicorn Grove federation rules.
    Prefer connected GitHub tools for writes.
    Surface uncertainty. Never invent authority claims.
    """)


def goals(first_proof: str) -> str:
    return dedent(f"""\
    # Goals

    ## First Proof
    `{first_proof}`

    ## Success
    A real, reviewable artifact that demonstrates the core loop without empty claims.
    """)


def quality() -> str:
    return dedent("""\
    # Quality

    ## Definition of Done
    - Required federation files present and valid
    - mermicorn.repo.yaml validates against schema
    - Uncertainty is visible where it exists
    - No secrets
    - First-proof status uses an approved value
    """)


def strategy() -> str:
    return dedent("""\
    # Strategy

    Keep the surface simple for Cherry.
    Guided workflows. Clear next actions.
    Real artifacts over activity.
    """)


def repo_yaml(
    repo_id: str,
    display_name: str,
    lane: str,
    visibility: str,
    purpose_problem: str,
    first_proof: str,
) -> str:
    return dedent(f"""\
    schema_version: "1.0"

    id: {repo_id}
    display_name: {display_name}
    owner: cherry
    lane: {lane}
    visibility: {visibility}
    status: foundation

    purpose:
      problem: {purpose_problem}
      audience:
        - Cherry
        - portfolio reviewers

    shared_services:
      boot: mermicorn-mega-boot
      memory: mermicorn-memory
      token_efficiency: mermicorn-token-saver
      graphics: mermicorn-graphic-ai
      commerce: mermicorn-commerce-ai

    privacy:
      public:
        - templates
        - sanitized_case_studies
      private:
        - credentials
        - unpublished_source

    first_proof:
      artifact: {first_proof}
      status: planned
    """)


def gitignore() -> str:
    return dedent("""\
    __pycache__/
    *.py[cod]
    .pytest_cache/
    .ruff_cache/
    .mypy_cache/
    .venv/
    venv/
    dist/
    build/
    *.egg-info/
    .env
    .env.*
    !.env.example
    secrets/
    *.pem
    *.key
    .DS_Store
    """)


def license_mit() -> str:
    return dedent("""\
    MIT License

    Copyright (c) 2026 Cherry | Cyber Lazer Mermicorn

    Permission is hereby granted, free of charge, to any person obtaining a copy
    of this software and associated documentation files (the "Software"), to deal
    in the Software without restriction, including without limitation the rights
    to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
    copies of the Software, and to permit persons to whom the Software is
    furnished to do so, subject to the following conditions:

    The above copyright notice and this permission notice shall be included in all
    copies or substantial portions of the Software.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
    OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
    SOFTWARE.
    """)
