"""Deterministic templates for a compliant Mermicorn repository."""

from __future__ import annotations

from textwrap import dedent


def readme(
    display_name: str,
    purpose_problem: str,
    first_proof: str,
    lane: str,
) -> str:
    return dedent(f"""\
    # {display_name}

    ## 1. What this project does
    {purpose_problem}

    ## 2. Who it is for
    Cherry and the Mermicorn Grove operators.

    ## 3. What exists today
    Foundation structure generated by mermicorn-mega-boot.

    ## 4. What is planned
    First proof artifact: `{first_proof}`.

    ## 5. What it does not claim
    No secrets, no false authority claims, no empty theater.

    ## 6. First proof artifact
    `{first_proof}`

    ## 7. Shared Mermicorn services
    See `mermicorn.repo.yaml` and the canonical registry at [mermicorn-grove](https://github.com/cyber-lazer-mermicorn/mermicorn-grove).

    ## 8. Information that remains private
    Secrets, credentials, and operational records stay in private layers or an external vault.

    ---
    *Generated by mermicorn-mega-boot. Proprietary — see LICENSE / RIGHTS.md. Collaboration by discussion.*
    """)


def status() -> str:
    return dedent("""\
    # Status

    **State:** FOUNDATION
    **Last updated:** generated by mermicorn-mega-boot

    Next: implement the first proof artifact declared in `mermicorn.repo.yaml`.
    """)


def roadmap(first_proof: str) -> str:
    return dedent(f"""\
    # Roadmap

    1. Complete foundation (done by mega-boot)
    2. Deliver first proof: `{first_proof}`
    3. Harden quality gates and examples
    4. Publish or promote when verified
    """)


def architecture() -> str:
    return dedent("""\
    # Architecture

    Follows the Mermicorn shared contract.
    Canonical integration state lives in mermicorn-grove.
    This repository owns its domain surface only.
    """)


def security() -> str:
    return dedent("""\
    # Security

    - No passwords, API keys, payment credentials, or government ID in this repository.
    - Use GitHub Secrets or an external vault for true secrets.
    - Public content is sanitized portfolio or template material only.
    """)


def contributing() -> str:
    return dedent("""\
    # Contributing

    Owned by Cherry (Cyber Lazer Mermicorn).
    This work is proprietary. Collaboration is open to discussion and requires a separate written agreement.
    See LICENSE and RIGHTS.md (and the canonical instrument in mermicorn-grove).
    Work on feature branches when authorized.
    Update STATUS.md and mermicorn.repo.yaml when state changes.
    Prefer atomic, descriptive commits.
    """)


def changelog() -> str:
    return dedent("""\
    # Changelog

    ## [Unreleased]
    - Scaffolded by mermicorn-mega-boot
    """)


def agents() -> str:
    return dedent("""\
    # Agents

    ## Primary Operator
    Cherry — domain judgment and final decisions.

    ## AI Support
    Operates under Mermicorn Grove federation rules.
    Prefer connected GitHub tools for writes.
    Surface uncertainty. Never invent authority claims.
    First pass is last pass. No placeholders.
    """)


def goals(first_proof: str) -> str:
    return dedent(f"""\
    # Goals

    ## First Proof
    `{first_proof}`

    ## Success
    A real, reviewable artifact that demonstrates the core loop without empty claims.
    """)


def quality() -> str:
    return dedent("""\
    # Quality

    ## Definition of Done
    - Required federation files present and valid
    - mermicorn.repo.yaml validates against schema
    - Uncertainty is visible where it exists
    - No secrets
    - First-proof status uses an approved value
    - First pass is last pass — no placeholder surfaces
    """)


def strategy() -> str:
    return dedent("""\
    # Strategy

    Keep the surface simple for Cherry.
    Guided workflows. Clear next actions.
    Real artifacts over activity.
    Proprietary core; collaboration by discussion and written agreement only.
    """)


def rights() -> str:
    return dedent("""\
    # Rights

    **Controlling instrument:** [Mermicorn Grove LICENSE](https://github.com/cyber-lazer-mermicorn/mermicorn-grove/blob/main/LICENSE)

    **© Cherry | Cyber Lazer Mermicorn. All rights reserved.**

    Original works are proprietary. Public viewing is allowed for information and portfolio evaluation.
    No general license to copy, modify, distribute, or commercialize except by separate written agreement signed by Cherry.

    Collaboration is open to discussion. Inquiries do not create rights.

    Governing law: State of Hawaiʻi and U.S. federal copyright law.
    Venue: First Circuit, Honolulu, Hawaiʻi.

    Not legal advice. Have counsel review for high-stakes use.
    """)


def proprietary_license_notice() -> str:
    return dedent("""\
    PROPRIETARY — ALL RIGHTS RESERVED

    Copyright © 2026 Cherry | Cyber Lazer Mermicorn

    This repository and its contents are proprietary.

    The controlling rights instrument for the Mermicorn Grove constellation is:

      https://github.com/cyber-lazer-mermicorn/mermicorn-grove/blob/main/LICENSE

    Mermicorn Grove Proprietary License and Rights Reservation, Version 1.0

    Public viewing of GitHub content for information and portfolio evaluation is permitted.
    No general license is granted to copy, modify, distribute, commercialize, or create
    derivative works except under a separate written agreement signed by the Owner.

    Collaboration is open to discussion. Inquiries do not create rights.

    Governing law: State of Hawaiʻi and applicable United States federal law.
    Venue: First Circuit, City and County of Honolulu, Hawaiʻi.

    See also RIGHTS.md in this repository and in mermicorn-grove.
    """)


def repo_yaml(
    repo_id: str,
    display_name: str,
    lane: str,
    visibility: str,
    purpose_problem: str,
    first_proof: str,
) -> str:
    return dedent(f"""\
    schema_version: "1.0"

    id: {repo_id}
    display_name: {display_name}
    owner: cherry
    lane: {lane}
    visibility: {visibility}
    status: foundation

    purpose:
      problem: {purpose_problem}
      audience:
        - Cherry
        - portfolio reviewers

    shared_services:
      boot: mermicorn-mega-boot
      memory: mermicorn-memory
      token_efficiency: mermicorn-token-saver
      graphics: mermicorn-graphic-ai
      commerce: mermicorn-commerce-ai

    privacy:
      public:
        - templates
        - sanitized_case_studies
      private:
        - credentials
        - unpublished_source

    first_proof:
      artifact: {first_proof}
      status: planned
    """)


def gitignore() -> str:
    return dedent("""\
    __pycache__/
    *.py[cod]
    .pytest_cache/
    .ruff_cache/
    .mypy_cache/
    .venv/
    venv/
    dist/
    build/
    *.egg-info/
    .env
    .env.*
    !.env.example
    secrets/
    *.pem
    *.key
    .DS_Store
    """)
